### ISSUE TITLE
Creating a session and generating a unique link to join session

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/RPG-Handy-Helper-Archived#10]
# Description
We need to find a way to create a "room" for players to join when gamemaster starts a session. Later on, we need to make players join this campaign.

# TODO
- [ ] Find a way to be able to create a shared room
- [ ] Generate a unique code to join the session
- [ ] let players be able to chat / see who is in the session (easier)
