### ISSUE TITLE
Email Sending

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/RPG-Handy-Helper-Archived#15]
# Description

Implement email sender using PHPMailer library, configure it and test out.

# TODO

- [x] install PHPMailer library
- [x] prepare nice emails templates
- [x] create class to handle email sending
- [x] configure `.env` variables
- [x] prepare a registration template for html
- [x] test out

**Comment by ZuberRS03** [comment]
Works fine, I got an email.

**Comment by xEdziu** [comment]
@ZuberRS03 you have to merge PR connected to this Issue, to close it instead of doing it manually.
