### ISSUE TITLE
Prepare database, tables and user DTO

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/RPG-Handy-Helper-Archived#7]
# Opis
Trzeba się zastanowić nad wyglądem całej bazy danych z informacjami o game masterach (gm). Możemy to zaprojektować przy użyciu [tego narzędzia](https://www.dbdesigner.net/) a następnie trzeba przygotować kontrolery obsługujące tę bazę danych. Temat do przegadania co i jak. Możemy zrobić jakieś osiągnięcia jak się będzie nam nudzić naprawdę.

# TODO

- [x] Przygotować schemat bazy danych
- [x] Zaprojektować i napisać klasę przygotowujące połączenie z bazą danych
- [x] Napisać klasę DTO jako reprezentację rekordu w bazie danych + CRUD w tej klasie
- [ ] Napisać klasę testującą wszystkie funkcje z klasy DTO

**Comment by xEdziu** [comment]
@ZuberRS03 in `User.php` I left you a TODO note explaining your task for this class and I will probably add more, so keep searching :)
